spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://example.org
          predicates:
            - Query=red, gree.

        - id: product_route
          uri: lb://catmall-product
          predicates:
             - Path=/api/product/**
          filters:
              - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: thirdparty_route
          uri: lb://catmall-thirdparty
          predicates:
             - Path=/api/thirdparty/**
          filters:
              - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: ware_route
          uri: lb://catmall-ware
          predicates:
             - Path=/api/ware/**
          filters:
              - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 99